obj-y += yas_mag_drv-yas537.o yas_mag_kernel.o
obj-$(CONFIG_SENSORS_YAS_ACCELEROMETER_INPUT)+= yas_acc_drv-bma250e.o yas_acc_kernel.o
#obj-$(CONFIG_SENSORS_YAS_MAGNETOMETER_INPUT) += yas_mag_drv-yas537.o yas_mag_kernel.o
#obj-$(CONFIG_SENSORS_YAS_ACCELEROMETER_INPUT)+= yas_acc_drv-bma250e.o yas_acc_kernel.o

