# Makefile for the Himax touchscreen drivers.

obj-$(CONFIG_TOUCHSCREEN_HIMAX_I2C)   	+= himax_platform.o himax_852xES.o

#ifeq ($(TARGET_BUILD_VARIANT),user)
#ifeq ($(TARGET_BUILD_VARIANT),eng)
#ifeq ($(CEI_BUILD_SKU),CEI_FACTORY)
#	KBUILD_CFLAGS += -DTP_ENG_NODE
#endif

